# This workflow will upload a Python package using Twine when a release is
# created. For more information see the following link:
#     https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: Publish to PyPI

on:
  - push

jobs:
  deploy:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest

    # https://github.com/pypa/gh-action-pypi-publish#trusted-publishing
    permissions:
      id-token: write   # IMPORTANT: this permission is mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/deepsensor

    steps:
      - name: Publish distribution ğŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true